### PR TITLE
feat: add semantic-pull-request

### PR DESCRIPTION
**Pull request by kenji-miyake**

### CODE REVIEW

**Comment by kenji-miyake** [comment]
TODO: `pull_request` should be replaced by `pull_request_target` so that outside collaborators can run this workflow with `GITHUB_TOKEN`.

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target

**Comment by kenji-miyake** [comment]
Worked.
https://github.com/tier4/autoware-github-actions/runs/4294171207?check_suite_focus=true

**Comment by kenji-miyake** [comment]
`pull_request_target` won't run before merged, it's the same behavior as `workflow_dispatch`.

image

**Comment by kenji-miyake** [comment]
Waiting for #11 to be merged.

**Comment by kenji-miyake** [comment]
Since this adds a reusable workflow, I'll mark this as `feat`.

**Review by KeisukeShima — APPROVED** [review]

**Pull request merged**
