### PR TITLE
style: simplify curl options

### PR DESCRIPTION
**Pull request by kenji-miyake**
`fsSL` is commonly used.

- https://brew.sh/
- https://docs.docker.com/engine/install/ubuntu/

Sometimes there is no `L`, which is for the redirect.

- https://www.rust-lang.org/tools/install

In order to make it simple, I'd like to use shorter options.

### CODE REVIEW

**Comment by kmiya** [comment]
The use of long option names is intended. IMHO, `fsSL` seems to be difficult to understand.
まあどうでもいいので好きにしてください。

**Comment by kenji-miyake** [comment]
Thank you for your comment. :smile: 

> IMHO, fsSL seems to be difficult to understand.

I feel long options are more difficult. So it depends on the developer.
It's better to decide based on the common usages.

At least, we have to add `-f(--fail)` option to be able to notify failures like URL mistakes.

```sh
❯ curl --silent --show-error --output create-doc-comment.sh https://raw.githubusercontent.com/tier4/autoware-github-actions/foo/.github/create-doc-comment.sh

❯ cat create-doc-comment.sh 
404: Not Found⏎

❯ curl --fail --silent --show-error --output create-doc-comment.sh https://raw.githubusercontent.com/tier4/autoware-github-actions/foo/.github/create-doc-comment.sh
curl: (22) The requested URL returned error: 404                                                                                                                                                                                          
```

Also, please try to feel the shared ownership to any of our code.
https://docs.ros.org/en/foxy/Contributing/Developer-Guide.html#general-principles

So I believe nothing is "どうでもいい". But "どちらでもいい" is acceptable!

**Comment by KeisukeShima** [comment]
In my opinion, the longer options are easier to read. Short options are useful for typing on the console.
I will review this discussion after it is resolved.

**Comment by kenji-miyake** [comment]
@KeisukeShima Thank you for your comment! What do you mean by `after it is resolved`? :thinking:

**Comment by KeisukeShima** [comment]
> @KeisukeShima Thank you for your comment! What do you mean by `after it is resolved`? thinking

Thanks for letting me know. I mean `I will review after this discussion is resolved`.

**Comment by kenji-miyake** [comment]
（何か認識が合ってなさそうなので日本語で…）
どちらでも良いとおっしゃっているので、解決しているとは思います？

**Review by KeisukeShima — APPROVED** [review]

**Pull request merged**
