### PR TITLE
Add dependabot.yaml

### PR DESCRIPTION
**Pull request by KeisukeShima**

### CODE REVIEW

**Review by kenji-miyake — APPROVED** [review]
[Nits] Create -> Add is more natural? :thinking:

**Review by kenji-miyake — CHANGES_REQUESTED** [review]
Ah, sorry, could you confirm whether we can use `.yaml`?

**Comment by kenji-miyake** [comment]
https://yaml.org/faq.html
> Please use ".yaml" when possible.

**Comment by KeisukeShima** [comment]
Umm...

image

**Comment by KeisukeShima** [comment]
@kenji-miyake 
If the filename is `dependabot.yml`, vscode-icons recognizes file type.
image

After I changed filename to yaml, vscode-icons does not recognize file type.
image

**Comment by kenji-miyake** [comment]
Seems it works.
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/.github/dependabot.yaml

> After I changed the filename to yaml, the vscode-icons does not recognize file type.

I think you can send a PR to fix it.
I believe every tool needs to support both `.yaml` and `.yml` and that unifying naming rules is important.

**Comment by KeisukeShima** [comment]
> Seems it works. https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/.github/dependabot.yaml
> 
> > After I changed the filename to yaml, the vscode-icons does not recognize file type.
> 
> I think you can send a PR to fix it. I believe every tool needs to support both `.yaml` and `.yml` and that unifying naming rules is important.

Okay, that's a problem with the tool. We should use the recommended way.

**Review by kenji-miyake — APPROVED** [review]

**Pull request merged**
